### ISSUE TITLE
Not able to build for ios simulator arm64

### ISSUE THREAD

**Issue by vemarav** [mrousavy/react-native-fast-tflite#60]
Showing Recent Errors Only
Building for 'iOS-simulator', but linking in object file (/Users/vemarav/Developer/example/node_modules/react-native-fast-tflite/ios/TensorFlowLiteC.framework/TensorFlowLiteC) built for 'iOS'

**Comment by alexandreandriesse** [comment]
same problem

**Comment by metinaltinbas** [comment]
same here any solutions ?

**Comment by vemarav** [comment]
This can be solved using ios and ios-simulator folders, and xcode will automatically pick it up.

cc: @mrousavy

**Comment by alexandreandriesse** [comment]
I tried to duplicate the folder ios of the react-native-fast-tflite node_module, and renamed it to "ios_simulator", but the build continue to fail.

**Comment by mrousavy** [comment]
> This can be solved using ios and ios-simulator folders, and xcode will automatically pick it up.
> 
> cc: @mrousavy

What exactly do you mean by that? If you have an idea, it would be great if you could submit a PR, as I tried to add iOS simulator support but I didn't manage to properly build the core TFLite library for simulators.

**Comment by mdeividas** [comment]
I managed to solve this issue using rosetta simulator. Mode details [here](https://stackoverflow.com/questions/63607158/xcode-building-for-ios-simulator-but-linking-in-an-object-file-built-for-ios-f).

cc// @alexandreandriesse

**Comment by whw** [comment]
MacBook Pro M1 Sonoma 14.4.1
Xcode 15.3
react-native-fast-tflite @ latest

Yeh I ended up getting hooked by this as well. @mdeividas @vemarav could you share more on what you did to get it working?

Things I tried:
- Adding the extra config to the end of the `Podfile` (as specified by the SO answers)
- Excluding arm64 architecture for iOS-Simulator in Build Settings inside XCode (this one is shaky because I don't have a ton of XCode experience)
- Tried a separate ios-simulator folder, althoughwithout more xcode knowledge not sure how this was supposed to work

**Comment by nathangabriel27** [comment]
same problem

**Comment by vemarav** [comment]
This will fix the issue [#74 ](https://github.com/mrousavy/react-native-fast-tflite/issues/74#issuecomment-2175735359)
